sudo: required

language: python

python:
  - 3.5

os:
  - linux

cache:
  directories:
  - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install -r requirements.txt

script:
  - python src/test.py
